### ISSUE TITLE
not working with wiimote

### ISSUE THREAD

**Issue by SevenChords** [toy/blueutil#20]
I try to connect my wiimote via bluetooth, which worked fine before macos forced a bluetooth pin to connect, but the wiimotes don't have a bluetooth pin, and since dolphin could connect it (wasn't usable outside of dolphin), i imagined this could too, but appearently this can't connect to devices that simply don't have a bluetooth pin either, was wondering if this is a bug with the current version of this tool or if it has become literally impossible to connect bluetooth devices that don't have a bluetooth pin.

**Comment by toy** [comment]
By dolphin you mean https://dolphin-emu.org/?
Do you get output from the tool and can you share it?
I don't have a wiimote, but when developing the pairing functionality I was testing it on different devices including one without a pin and one with a default pin.

**Comment by toy** [comment]
@SevenChords Would you like to continue discussing your issue?

**Comment by toy** [comment]
Closing due to absence of reply. Please reopen or open a new issue if you would like to discuss the issue.

**Comment by gingerbeardman** [comment]
This is still not working, I'm on Monterey and it seems according to other issues it is an unresolved macOS bug.

Curious that [Wii4SESlogger](https://stemed.online/wiimote/) which uses `blueutil` behind the scenes to pair and connect shows a screenshot that implies it works on macOS Monterey.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/49612/226436627-989bd06f-1bf8-4590-9e74-a0933db71091.png">
