### ISSUE TITLE
'Failed to connect' error on recognized Apple Magic Trackpad 2

### ISSUE THREAD

**Issue by dhowe** [toy/blueutil#21]
```
$ blueutil --inquiry
address: ec-2c-e2-ef-44-0f, not connected, not favourite, not paired, name: "Magic Trackpad 2", recent access date: (null)

$ blueutil --connect ec-2c-e2-ef-44-0f
Failed to connect "ec-2c-e2-ef-44-0f"

```

Any thoughts or suggestions?!

**Comment by toy** [comment]
From the output of inquiry, it doesn't seem to be recognised. Did you try connecting through UI?

**Comment by toy** [comment]
@dhowe Would you like to continue discussing your issue?

**Comment by dhowe** [comment]
Sorry, don't have access to a trackpad anymore, but yes, I could connect consistently through the UI, but not from the command line

**Comment by toy** [comment]
Unfortunately I don't see a way to debug this issue unless you get access back or someone else comes with the same problem. I've tried unpairing and initiating pairing, and multiple rounds of connecting/disconnecting on previous version of trackpad, but I don't have access to the new one.
