### ISSUE TITLE
No option to add/remove favourites

### ISSUE THREAD

**Issue by Trophonix** [toy/blueutil#29]
What is the point of listing favourites if not able to add or remove them?

**Comment by toy** [comment]
API is there, so should be possible to implement. I'm not sure if I didn't try or tried and there was some problem.

**Comment by toy** [comment]
Seems to work for me, please have a look and if possible try [manage-favourites](https://github.com/toy/blueutil/tree/manage-favourites) branch

**Comment by toy** [comment]
@Trophonix ^^
