### ISSUE TITLE
Unpair device

### ISSUE THREAD

**Issue by mihaicris** [toy/blueutil#32]
How can I unpair a device?

Thanks!

**Comment by toy** [comment]
Please check #31

**Comment by mihaicris** [comment]
OK!

**Comment by toy** [comment]
@mihaicris I've stumbled upon an undeclared method allowing unpairing functionality, it is available with just released v2.9.0, details in [comment for #46](https://github.com/toy/blueutil/issues/46#issuecomment-832326520).
