### ISSUE TITLE
battery display

### ISSUE THREAD

**Issue by alanhg** [toy/blueutil#34]
I've noticed that if it's an apple device, you can see the power in a Bluetooth-managed location.

Can I get power information for these devices?

like this https://gist.github.com/miyagawa/ed22215692e1937ab4bc

**Comment by toy** [comment]
There is no such functionality in `blueutil`. There is `ioreg` which is used at the link you gave and its functionality can probably be reproduced using IOKit, but not sure if non apple devices are giving information. There is also [Akku app](https://github.com/jariz/Akku) which I assume is more universal, but looking at ammount of code it is apparently is pretty complex.

**Comment by alanhg** [comment]
@toy 

Thank you, I'll try ioreg

**Comment by alanhg** [comment]
I found solution 

 https://apple.stackexchange.com/questions/328091/airpods-battery-level-with-ioreg
