### ISSUE TITLE
Release Tarballs

### ISSUE THREAD

**Issue by beren12** [toy/blueutil#37]
Could you please issue release tarballs so it's easier for people to download a specific version of the source? It can also be checksummed/signed so there is no doubt it hasn't been modified

**Comment by toy** [comment]
Tarballs for releases are already there https://github.com/toy/blueutil/releases and after some searching it seems that unlike archives linked at https://github.com/toy/blueutil/tags they are stable.
But checksums should be easy to add to releases, not sure whether putting them in description or as files like `blueutil-2.6.0.tar.gz.sha256` is better. Signatures on the other hand are more involved.

**Comment by beren12** [comment]
Sorry, looks like github's new layout got me. So much for an improvement… I was looking for them at the top not hidden in the sidebar. Checksums are likely good enough in the description if it's not too much work.

**Comment by toy** [comment]
You are not alone, it took me some time to find the link 😄 
Created a release out of latest tag: https://github.com/toy/blueutil/releases/tag/v2.6.0, I'll see how to better organise checking and checksumming archives to add description in future releases

**Comment by beren12** [comment]
Oh. I just saw firefox had this repo open... there was *no* releases link anywhere when I opened the bug, not until I refreshed just now and it appeared. so I *wasn't* crazy/blind.

**Comment by toy** [comment]
Created [releases for each tag with checksums](https://github.com/toy/blueutil/releases), so I assume this can be closed :)
