### ISSUE TITLE
Conflicting usage information

### ISSUE THREAD

**Issue by PaulCapestany** [toy/blueutil#4]
Just wanted to give you a heads up that http://www.frederikseiffert.de/blueutil/ happens to have pretty outdated usage information (from a superficial scan of your commits it seems like it'd probably be around cc07347fc0547aba5b29b98f4cc0753608fab375). 

Not a big deal, though in my case it briefly made me think this utility was broken—luckily it's not though, thanks for making it! 👍

**Comment by toy** [comment]
You've triggered a [cleanup](https://github.com/toy/blueutil/compare/cleanup?expand=1) :D
Would be awesome if you could check if `make` runs successfully for you on branch `cleanup` and especially if you could check that brew works with this changes.

**Comment by PaulCapestany** [comment]
Nice! RE: running `make` on the cleanup branch, it seemed like `-Werror` was preventing it from working for me, see https://github.com/toy/blueutil/pull/5

RE: homebrew, it seems that formulas have changed a bit since the last time I submitted one, will see if I read through https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md to refresh my memory.

**Comment by toy** [comment]
Fun to debug such stuff using a bluetooth keyboard/touchpad :D

**Comment by toy** [comment]
But the warning were important ones, unfortunately not reported by my gcc. Too much ruby for me, I've forgot how `||` works in C.
