### ISSUE TITLE
[Localization] Support US spelling in list/add/remove favorite

### ISSUE THREAD

**Issue by micahhausler** [toy/blueutil#49]
It would be great to support handling the US spelling of the `--favourites`/`--add-favourite`/`--remove-favourite` flag, even if the help text displays the British spelling.

**Comment by toy** [comment]
😄  Nice, thank you for opening the issue! Definitely makes sense.

**Comment by toy** [comment]
It will be great if you could try the version at [us-spelling branch](https://github.com/toy/blueutil/compare/us-spelling)
