### ISSUE TITLE
Can't connect/disconnect by device name on Monterey

### ISSUE THREAD

**Issue by malcolmsailor** [toy/blueutil#62]
Hi, since upgrading to Monterey, I can no longer use device names (e.g., 'STR-DH190') with commands like `blueutil --connect` or `blueutil --disconnect`. This isn't a huge problem since addresses like `3c-91-80-1a-e6-ba` still work.

FWIW I also have the same issue with `--disconnect` mentioned in #58 ; either of the workarounds (adding `--info` or `--wait-disconnect`) mentioned in that thread work.

**Comment by deeeeekun** [comment]
Having the same issue on Sonoma

**Comment by toy** [comment]
@deeeeekun If you list recent devices (`blueutil --recent`), do you see the name that you use?

**Comment by deeeeekun** [comment]
@toy No, it doesn't show either

**Comment by toy** [comment]
You mean the list is empty or there are no names?
What about `blueutil --paired`?
For now only recent connected devices are used for device names, so if the list is empty or no names, blueutil will not be able to have devices referenced by name.

**Comment by deeeeekun** [comment]
The device (and device name) shows up in `blueutil --paired`. `blueutil --recent` returns an empty list, even though I have just connected to it (using the address).

**Comment by toy** [comment]
Looks like a good idea to make that blueutil first checks paired devices for names. Though absence of recent devices must be a bug, framework, or os installation/state issue.
