### ISSUE TITLE
blueutil compatibility

### ISSUE THREAD

**Issue by rfardy** [toy/blueutil#69]
Not an issue, per se. 

Just wondering about blueutil compatibility with devices such as Logitech which use the "Unifying Receiver". I was testing a couple of those last week. blueutil could not see the devices with --inquiry or --paired (after pairing via System Preferences - which would not be available to our users). That said, there was no Logitech device information in the plist, after pairing. I don't know much about this "Unifying Receiver" but it seems to interfere with the standard process or Logitech is storing the data elsewhere. Just wondering if you had any experience with such devices or knew of any caveats.

**Comment by toy** [comment]
Unifying Receiver is not using bluetooth, it is a proprietary protocol which only uses same range of frequencies. It has separate receiver which as far as I know is responsible for holding data on paired devices and presenting them to OS as HID devices. Protocol that is used by Logitech configuration software to communicate with dongles is also proprietary.
