### ISSUE TITLE
Connecting to a tethered Bluetooth network

### ISSUE THREAD

**Issue by shivaprsd** [toy/blueutil#74]
Hi, thanks for this utility.

Is it possible to connect to Bluetooth PAN using `blueutil`? I mean the equivalent of right clicking on a connection and choosing 'Connect to network' in the GUI.

I think `networksetup` might be the correct tool for this; anyway thought to ask here. 🙂

**Comment by toy** [comment]
Creating/enablying/connecting to device network is currently out of scope for `blueutil`. So connecting bluetooth device using `blueutil` and then probably using `networksetup` :)

**Comment by shivaprsd** [comment]
I thought so. However since the GUI is in the Bluetooth Preferences, I thought the API could be among those `blueutil` uses.

I haven't found a way with `networksetup`. Most guides online only show how to connect to WiFi. 😕
