### ISSUE TITLE
Add a "--power toggle" option

### ISSUE THREAD

**Issue by lhaeger** [toy/blueutil#8]
In order to utilize blueutil with keyboard tools like Better Touch Tools or similar, a command line option to toggle the power state would be helpful. 
The toggle option should basically do the same as this applescript (which I have assigned to the "Fn-B" hotkey via BTT), just without the need for a script in the first place:

```
set blueutil to "/usr/local/bin/blueutil"
set powerStatus to do shell script blueutil & " --power"

if powerStatus is "1" then
	do shell script blueutil & " --power off"
else if powerStatus is "0" then
	do shell script blueutil & " --power on"
end if
```

**Comment by toy** [comment]
Please have a look/check how d4b456b9006d16cf72cc472f3afee19e1b8f0777 works for you.

**Comment by lhaeger** [comment]
Seems to do the trick rather nicely. Thanks a lot, Ivan!

**Comment by toy** [comment]
v2.1.0 is out
