### ISSUE TITLE
How to add favorite?

### ISSUE THREAD

**Issue by mattdee** [toy/blueutil#81]
I attempt to add all my device to favorites with the following script:

```
for i in $(blueutil --paired | awk '{print $2}' | sed 's/,//g')                                                                                                                                                                                  
do
blueutil --add-favourite $i
blueutil --favourites
done
```

How do I add a device to favorites?

Thanks,
Matt

**Comment by m-graf** [comment]
Not the OP – but I am also having this issue. 


➞  blueutil --info 00-1f-20-27-7c-1a                                                                                                   address: 00-1f-20-27-7c-1a, connected (master, -51 dBm), not favourite, paired, name: "Logitech MX Revolution Mouse", recent access date: 2024-05-08 18:01:43 +0000
➞  blueutil --add-favourite 00-1f-20-27-7c-1a                                                                                          ➞  blueutil --favourites                                                                                                               
➞

**Comment by toy** [comment]
@mattdee @m-graf Unfortunately the favourites logic is apparently deprecated and is not working since some version of osx (probably Monterey), I've documented it in the tool [in v2.10.0](https://github.com/toy/blueutil/blob/main/CHANGELOG.md#v2100-2024-04-28)
