### ISSUE TITLE
Incorrect Recent Access Date

### ISSUE THREAD

**Issue by dalegallosky** [toy/blueutil#84]
Hello, 

When attempting --paired I see all my devices but the recent access date all shows the current date/time. Using --info with the MAC address results in similar results. Terminal access is toggled on for both Developer Tools and Bluetooth, and I restarted Terminal. 

MacOS 14.3.

Thank you!

![1](https://github.com/toy/blueutil/assets/157847992/cf686917-8724-4dd3-b51f-9123d584a5bf)

**Comment by toy** [comment]
The value for recent access date is coming directly from framework, code just gets paired devices and prints the values. I can suggest trying to restart and check if possible on different machine.

**Comment by dalegallosky** [comment]
Thanks - confirmed issue occurs on three different machines - two Apple silicon; one Intel.

**Comment by toy** [comment]
I've checked on available machines and seems it got broken in the framework between Catalina and Monterey. Looks like only submitting a bug to Apple can help with this.

**Comment by toy** [comment]
While checking for #89 I thought that it is probably not a bug, but either privacy feature or just functionality that was silently removed, so I'll document it
